#  Write a program "nearly_equal.py" to check whether two given strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b. 
# For example,
# if str1="'python", str2="'perl", it should return False, 
# if  str1="'python", str2="jython", it should return True, and
# if  str1="man", str2="'woman", it should return False.


str1 = input("enter string1: ")
str2  = input("enter string2: ")
if len(str1) != len(str2):
    print("false")
count = 0
for i in range(len(str1)):
    if str1[i] != str2[i]:
        count+=1
if count == 1:
    print("true")
else:
    print("false")